# Run several Python linters on all Python files in this repository
name: Lint checks
on: [push, pull_request]
jobs:
  python:
    strategy:
      fail-fast: false
      matrix:
        version: ['3.12', '3.11', '3.10', '3.9', '3.8']
    uses: ClangBuiltLinux/actions-workflows/.github/workflows/python_lint.yml@main
    with:
      python_version: ${{ matrix.version }}
