# Run shellcheck and shfmt on all shell files and yapf on all Python files in this repository
name: Lint checks
on: [push, pull_request]
jobs:
  shellcheck:
    uses: ClangBuiltLinux/actions-workflows/.github/workflows/shellcheck.yml@main
  shfmt:
    uses: ClangBuiltLinux/actions-workflows/.github/workflows/shfmt.yml@main
  yapf:
    uses: ClangBuiltLinux/actions-workflows/.github/workflows/yapf.yml@main
